backend:
  name: proxy
  branch: main 
  proxy_url: /.netlify/functions/auth

auth:
  provider: auth0
  domain: dev-0wyo82izwfochqny.us.auth0.com
  client_id: RUPzyznW1sNhlfpkKHAw2xmzoIQup5EF
  
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}